# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Aaron Lo/Documents/FPGA/OutOfOrderProcessor/OutOfOrderProcessor.srcs/sources_1/bd/OOOP/ip/OOOP_clk_wiz_0/OOOP_clk_wiz_0.xci
# IP: The module: 'OOOP_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Aaron Lo/Documents/FPGA/OutOfOrderProcessor/OutOfOrderProcessor.gen/sources_1/bd/OOOP/ip/OOOP_clk_wiz_0/OOOP_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'OOOP_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Aaron Lo/Documents/FPGA/OutOfOrderProcessor/OutOfOrderProcessor.gen/sources_1/bd/OOOP/ip/OOOP_clk_wiz_0/OOOP_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'OOOP_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Aaron Lo/Documents/FPGA/OutOfOrderProcessor/OutOfOrderProcessor.gen/sources_1/bd/OOOP/ip/OOOP_clk_wiz_0/OOOP_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'OOOP_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Aaron Lo/Documents/FPGA/OutOfOrderProcessor/OutOfOrderProcessor.srcs/sources_1/bd/OOOP/ip/OOOP_clk_wiz_0/OOOP_clk_wiz_0.xci
# IP: The module: 'OOOP_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Aaron Lo/Documents/FPGA/OutOfOrderProcessor/OutOfOrderProcessor.gen/sources_1/bd/OOOP/ip/OOOP_clk_wiz_0/OOOP_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'OOOP_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Aaron Lo/Documents/FPGA/OutOfOrderProcessor/OutOfOrderProcessor.gen/sources_1/bd/OOOP/ip/OOOP_clk_wiz_0/OOOP_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'OOOP_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Aaron Lo/Documents/FPGA/OutOfOrderProcessor/OutOfOrderProcessor.gen/sources_1/bd/OOOP/ip/OOOP_clk_wiz_0/OOOP_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'OOOP_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
